  "use client"
  import ThemeRegistry from "@/theme/ThemeRegistry";
  import Navbar from "@/app/components/navbar/Navbar";
  import Grid from '@mui/material/Grid';
  // import "./globals.css";
  import { Inter } from "next/font/google";

  const inter = Inter({ subsets: ["latin"] });

  export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
      <html lang="en">
        <ThemeRegistry>
          <body className={inter.className}>
            <Grid container sx={{height: '100vh'}}>
              <Grid item xs={2} sx={{backgroundColor: '#101F33',}}>
                <Navbar />
              </Grid>
              <Grid item xs={10}>
                {children}
              </Grid>
            </Grid>
          </body>
        </ThemeRegistry>
      </html>
    );
  }
